module.exports = {
    theme: {
        colors: {
            transparent: 'transparent',
            black: 'var(--black)',
            'gray-darkest': 'var(--gray-darkest)',
            'gray-darker': 'var(--gray-darker)',
            'gray-dark': 'var(--gray-dark)',
            gray: 'var(--gray)',
            'gray-light': 'var(--gray-light)',
            'gray-lighter': 'var(--gray-lighter)',
            'gray-lightest': 'var(--gray-lightest)',
            white: 'var(--white)',
            paper: 'var(--paper)',
            'paper-dark': 'var(--paper-dark)',
            'paper-darker': 'var(--paper-darker)',
            'paper-darkest': 'var(--paper-darkest)',
            blue: 'var(--blue)',
            'blue-dark': 'var(--blue-dark)',
        },
        fontFamily: {
            title: [
                'Fugaz One',
                'system-ui',
                'BlinkMacSystemFont',
                '-apple-system',
                'Segoe UI',
                'Roboto',
                'Oxygen',
                'Ubuntu',
                'Cantarell',
                'Fira Sans',
                'Droid Sans',
                'Helvetica Neue',
                'sans-serif',
            ],
            sans: [
                'ff-meta-web-pro',
                'system-ui',
                'BlinkMacSystemFont',
                '-apple-system',
                'Segoe UI',
                'Roboto',
                'Oxygen',
                'Ubuntu',
                'Cantarell',
                'Fira Sans',
                'Droid Sans',
                'Helvetica Neue',
                'sans-serif',
            ],
            serif: ['pt-serif'],
            mono: ['Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        },
        extend: {
            borderColor: {
                default: 'var(--gray-light)',
            },
        },
    },
};
